BEGIN;
DO $test$
declare u uuid:=gen_random_uuid();other_user uuid:=gen_random_uuid();module text;a jsonb;aid uuid;r boolean;n integer;
begin
 select module_key into module from public.training_question_bank where active=true group by module_key having count(*)>=5 limit 1;
 insert into auth.users(id,email) values(u,u::text||'@example.invalid'),(other_user,other_user::text||'@example.invalid');
 perform set_config('request.jwt.claim.sub',u::text,true);
 execute 'set local role authenticated';
 select count(*) into n from public.training_question_bank;
 assert n=0,'direct question bank must be denied';
 a:=public.start_training_attempt(module,5);aid:=(a->>'attempt_id')::uuid;
 assert not exists(select 1 from jsonb_array_elements(a->'questions') q where q ? 'correct_answer' or q ? 'explanation'),'start must not expose answer key';
 select count(*) into n from public.training_attempt_review(aid);
 assert n=0,'incomplete attempt must not expose answers';
 execute 'reset role';
 perform set_config('request.jwt.claim.sub',other_user::text,true);
 execute 'set local role authenticated';
 r:=false;
 begin perform public.submit_training_attempt(aid,'{}'::jsonb); exception when others then r:=SQLERRM='Attempt not found'; end;
 assert r,'other user must not submit attempt';
 execute 'reset role';
 perform set_config('request.jwt.claim.sub',u::text,true);
 execute 'set local role authenticated';
 perform public.submit_training_attempt(aid,'{}'::jsonb);
 select count(*) into n from public.training_attempt_review(aid);
 assert n=5,'own completed attempt must support review';
 r:=false;
 begin perform public.submit_training_attempt(aid,'{}'::jsonb); exception when others then r:=SQLERRM='Attempt already submitted'; end;
 assert r,'resubmission must fail';
 execute 'reset role';
 perform set_config('request.jwt.claim.sub',other_user::text,true);
 execute 'set local role authenticated';
 select count(*) into n from public.training_attempt_review(aid);
 assert n=0,'other user must not see completed answer review';
 execute 'reset role';
end;
$test$;
ROLLBACK;
SELECT 'PASS: direct bank denied, no answer key before submission, own completed review allowed, cross-user access and resubmission denied; fixtures rolled back' result;
